# Meta
env: production
title: CustumerJourney.js
description: Open Source Vanilla Javascript Libraries for Building Touchpoints as a System.
baseurl: "" # Ajusta a "/nombre-repositorio" si es necesario
#url: "" # Dejar vacío para que Jekyll lo infiera

# Build
lsi: false
safe: true
#source: git@github.com:antoniofregoso/customerjourney.github.io.git
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scss/
  - package.json
  - package-lock.json
  - custumerjourney.github.io.code-workspace

#sass:
#  style: compressed
#  sass_dir: _sass 


