# Meta
env: development
title: Mi Sitio Jekyll
description: Un sitio generado con Jekyll
baseurl: "" # Ajusta a "/nombre-repositorio" si es necesario
url: "" # Dejar vacío para que Jekyll lo infiera

# Build
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scss/
  - package.json
  - package-lock.json
  - buyerjourney.github.io.code-workspace

sass:
  style: compressed
  sass_dir: _sass # Asegúrate de que coincida con tu carpeta Sass


