# Meta
env: production
title: CustomerJourney.js  # Corregido: "Customer" con 'o'
description: Open Source Vanilla Javascript Libraries for Building Touchpoints as a System.
baseurl: "/customerjourney" # Debe coincidir EXACTAMENTE con el nombre del repo
url: "https://antoniofregoso.github.io"
permalink: /:name/

# Build
lsi: false
safe: true
incremental: false
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _scss/
  - package.json
  - package-lock.json
  - "*.code-workspace" # Para excluir cualquier archivo de espacio de trabajo